services:
  app-backend:
    build: {
      context: ./,
      dockerfile: docker/node/Dockerfile
    }
    restart: always
    ports:
      - '3001:3001'
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./api:/usr/node/app/src

  db:
    image: mongo:8.0.1
    restart: always
    ports:
      - '27017:27017'