services:
  app-backend:
    build: .
    restart: always
    ports:
      - '3001:3001'
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/usr/node/app/src

  db:
    image: mongo:8.0.1
    restart: always
    ports:
      - '27017:27017'