services:
  user-backend:
    build: {
      context: ./,
      dockerfile: docker/user/node/Dockerfile
    }
    restart: always
    ports:
      - '3001:3001'
    env_file:
      - ./api/user-service/.env
    depends_on:
      - user-db
    volumes:
      - ./api:/usr/node/app/src

  timer-backend:
    build: {
      context: ./,
      dockerfile: docker/timer/node/Dockerfile
    }
    restart: always
    ports:
      - '9000:9000'
    env_file:
      - ./api/timer-service/.env
    depends_on:
      - timer-db
    volumes:
      - ./api:/usr/node/app/src
    
  gateway-backend:
    build: {
      context: ./,
      dockerfile: docker/gateway/node/Dockerfile
    }
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - ./api/timer-service/.env
    volumes:
      - ./api:/usr/node/app/src

  user-db:
    build: {
      context: ./,
      dockerfile: docker/user/mongo/Dockerfile
    }
    restart: always
    ports:
      - '27017:27017'

  timer-db:
    build: {
      context: ./,
      dockerfile: docker/timer/mongo/Dockerfile
    }
    restart: always
    ports:
      - '27018:27017'